# Generated by Django 4.1.7 on 2023-05-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_doctor1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
