# Generated by Django 4.1.7 on 2023-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_patient_patientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor1',
            name='academic_degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor1',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
