# Generated by Django 4.2.1 on 2023-06-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='age_categories',
            field=models.CharField(choices=[('children', 'children'), ('teen', 'teen'), ('adult', 'adult')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
