# Generated by Django 4.2.1 on 2023-06-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_treatment_age_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='age_categories',
            field=models.CharField(choices=[('children', 'children'), ('teen', 'teen'), ('adult', 'adult')], max_length=20, verbose_name='Age Categories'),
        ),
    ]
