# Generated by Django 4.2.1 on 2023-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_alter_treatment_age_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
    ]
