# Generated by Django 4.2.1 on 2023-06-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor1',
            name='Doctor_Image',
            field=models.ImageField(default=0, upload_to='Doctor', verbose_name='Doctor Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='tImage',
            field=models.ImageField(default=12, upload_to='treatment', verbose_name='Treatment Image'),
            preserve_default=False,
        ),
    ]
