# Generated by Django 4.2.1 on 2023-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_doctor1_doctor_image_treatment_timage'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='befror_eating',
            field=models.BooleanField(default=True),
        ),
    ]
