# Generated by Django 4.2.1 on 2023-07-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_treatment_befror_eating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor1',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='cancer', verbose_name='patient_image'),
        ),
    ]
