# Generated by Django 4.2.1 on 2023-07-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0014_alter_doctor1_gender_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='patient',
        ),
    ]
