# Generated by Django 4.2.1 on 2023-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0015_remove_image_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='befror_eating',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='cancer',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.AddField(
            model_name='treatment',
            name='before_eating',
            field=models.BooleanField(default=True, verbose_name='Before Eating '),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage',
            field=models.IntegerField(verbose_name='Treatment Daily  Dosage '),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Treatment Name'),
        ),
    ]
